using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Reflection;

namespace Builder.Api.Services;

public sealed class CompileResult
{
    public byte[]? AssemblyBytes { get; init; }
    public string? Error { get; init; }
    public bool Success => Error is null && AssemblyBytes is { Length: > 0 };
}

/// <summary>
/// Compiles C# source (generated by the Next.js template builder) to a .NET assembly.
/// The source must contain a public static class PageRenderer with a
/// static string Render(IReadOnlyDictionary&lt;string,object?&gt; vb) method.
/// </summary>
public sealed class RazorCompiler
{
    private static readonly Lazy<IReadOnlyList<MetadataReference>> _references =
        new(BuildReferences, LazyThreadSafetyMode.ExecutionAndPublication);

    public CompileResult Compile(string csharpSource)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(csharpSource);

        var compilation = CSharpCompilation.Create(
            $"PageRenderer_{Guid.NewGuid():N}",
            [syntaxTree],
            _references.Value,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary,
                optimizationLevel: OptimizationLevel.Release,
                nullableContextOptions: NullableContextOptions.Enable));

        using var ms = new MemoryStream();
        var result = compilation.Emit(ms);

        if (!result.Success)
        {
            var errors = result.Diagnostics
                .Where(d => d.Severity == DiagnosticSeverity.Error)
                .Select(d => d.ToString());
            return new CompileResult { Error = string.Join("\n", errors) };
        }

        return new CompileResult { AssemblyBytes = ms.ToArray() };
    }

    /// <summary>
    /// Invokes the compiled Render method from stored assembly bytes.
    /// </summary>
    public static string Render(byte[] assemblyBytes, IReadOnlyDictionary<string, object?> viewBag)
    {
        var assembly = Assembly.Load(assemblyBytes);
        var type = assembly.GetTypes()
            .FirstOrDefault(t => t.Name == "PageRenderer")
            ?? throw new InvalidOperationException("PageRenderer class not found in compiled assembly.");

        var method = type.GetMethod("Render", BindingFlags.Public | BindingFlags.Static)
            ?? throw new InvalidOperationException("Render method not found on PageRenderer.");

        return (string)(method.Invoke(null, [viewBag])
            ?? throw new InvalidOperationException("Render returned null."));
    }

    private static IReadOnlyList<MetadataReference> BuildReferences()
    {
        // Use TRUSTED_PLATFORM_ASSEMBLIES to get all platform DLL paths
        var trustedPaths = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")
            ?.ToString()
            ?.Split(Path.PathSeparator)
            ?? [];

        var refs = trustedPaths
            .Where(File.Exists)
            .Select(p => (MetadataReference)MetadataReference.CreateFromFile(p))
            .ToList();

        // Also add any loaded assemblies not already covered
        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            if (asm.IsDynamic || string.IsNullOrEmpty(asm.Location))
                continue;
            if (!trustedPaths.Contains(asm.Location, StringComparer.OrdinalIgnoreCase))
                refs.Add(MetadataReference.CreateFromFile(asm.Location));
        }

        return refs;
    }
}
